SOURCE = "uk_sma_source.txt"
OUTPUT = "uk_sma_output.txt"
SPECIAL= "Information gotten from https://github.com/smashew/NameDatabases/blob/master/NamesDatabases/surnames/uk.txt\n"

with open(SOURCE, "r") as source:
    raw_data = source.readlines()

output = "# This was generated by dev_tools/uk_sma_parse.py\n"+SPECIAL+"\n>MAIN\n\n"

with open(OUTPUT, "w") as output_file:
    output_file.write(output)
    for i in raw_data:
        output_file.write(f"{i.rstrip()}::1\n")
